# Generated by Django 5.2.10 on 2026-01-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_computationrule_operation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computationrule",
            name="operation",
            field=models.CharField(
                choices=[
                    ("avg", "Average"),
                    ("min", "Minimum"),
                    ("max", "Maximum"),
                    ("sum", "Sum"),
                ],
                default="avg",
                max_length=16,
            ),
        ),
    ]
