# Generated by Django 5.2.10 on 2026-01-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_alter_dataset_code_alter_indicator_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="computationrule",
            name="params",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
